DROP TABLE IF EXISTS users;
CREATE TABLE users (
  user_id SERIAL NOT NULL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  hobbies VARCHAR(255) DEFAULT '',
  about VARCHAR(255) DEFAULT ''
);


DROP TABLE IF EXISTS post;
CREATE TABLE post (
  post_id SERIAL NOT NULL PRIMARY KEY,
  author_id INTEGER NOT NULL REFERENCES users(user_id),
  wall_id INTEGER NOT NULL REFERENCES users(user_id),
  text VARCHAR(240) NOT NULL,
  pub_date TIMESTAMP
);

DROP TABLE IF EXISTS likes;
CREATE TABLE likes (
	like_id SERIAL NOT NULL PRIMARY KEY,
	post_id INTEGER NOT NULL REFERENCES post(post_id),
	user_id INTEGER NOT NULL REFERENCES users(user_id)
);